### PR TITLE
dbpedia: Also dump birtDate

### PR DESCRIPTION
**Pull request by mrshu**
* In order to estimate age of a person at the time we think an
  achievement took place.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
to @pepol 
cc @matejkrajcovic

**Comment by pepol** [comment]
LGTM
@mrshu: did you test this?

**Comment by mrshu** [comment]
@pepol briefly. It exports tons of stuff.

**Comment by pepol** [comment]
@mrshu okay, please fix commit message though: "birth date" instead of "birtDate".

**Comment by mrshu** [comment]
@pepol good point, thanks, should be fixed now.

**Comment by pepol** [comment]
@mrshu thanks! Merging this.

**Pull request merged**
