### PR TITLE
update: Unicode output for achievements

### PR DESCRIPTION
**Pull request by mrshu**
* Let's output parsed achievements encoded in unicode.

* Let's only take 10 pages on random if we have enough pages to do that.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
to @pepol

**Comment by pepol** [comment]
@mrshu why do we want to solve it like this?

**Comment by mrshu** [comment]
@pepol why not?

**Comment by pepol** [comment]
@mrshu oh, I didn't quite get it last night, sorry. LGTM anyway, merging this. Thanks!

**Pull request merged**
